// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAjCL8lbAdgQWFDrlg-Vw8ao0l3HI-ozg',
    appId: '1:643414683551:web:435efb461d6fbdeb3157aa',
    messagingSenderId: '643414683551',
    projectId: 'pbl7-2a6ad',
    authDomain: 'pbl7-2a6ad.firebaseapp.com',
    storageBucket: 'pbl7-2a6ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAvQbA3fcPHmeeZZ6457_QNb4O7FLtMn4',
    appId: '1:643414683551:android:95758a964e145ea83157aa',
    messagingSenderId: '643414683551',
    projectId: 'pbl7-2a6ad',
    storageBucket: 'pbl7-2a6ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBisuM0vfLUTC6scMZcbzz3KIBGRTojo9A',
    appId: '1:643414683551:ios:69e98e35f0db6c9c3157aa',
    messagingSenderId: '643414683551',
    projectId: 'pbl7-2a6ad',
    storageBucket: 'pbl7-2a6ad.firebasestorage.app',
    iosBundleId: 'com.example.appPbl7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBisuM0vfLUTC6scMZcbzz3KIBGRTojo9A',
    appId: '1:643414683551:ios:69e98e35f0db6c9c3157aa',
    messagingSenderId: '643414683551',
    projectId: 'pbl7-2a6ad',
    storageBucket: 'pbl7-2a6ad.firebasestorage.app',
    iosBundleId: 'com.example.appPbl7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAjCL8lbAdgQWFDrlg-Vw8ao0l3HI-ozg',
    appId: '1:643414683551:web:932e79472b329fdc3157aa',
    messagingSenderId: '643414683551',
    projectId: 'pbl7-2a6ad',
    authDomain: 'pbl7-2a6ad.firebaseapp.com',
    storageBucket: 'pbl7-2a6ad.firebasestorage.app',
  );
}
